name: Java CI and Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1: Build and Test (Requires MySQL Service) ---
  test:
    name: Build & Test (Linux Only)
    runs-on: ubuntu-latest # Services only work on Linux runners

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: parent_website
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: sleep 30s # Allow time for the service to spin up
        shell: bash

      - name: Build and Test with Maven (using Test Profile)
        run: mvn -B package --file pom.xml -Dspring.profiles.active=test

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  # --- JOB 2: Build and Push Docker Image ---
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest # Docker actions typically work best on Linux

    needs: test # Wait for tests to pass before building the image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # IMPORTANT: Replace 'demo-app' and ensure you have DOCKERHUB_USERNAME secret set
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest
